import { DataArchitecture, InternalConnection, DataNode, Connection } from '../types/ModelTypes';

/**
 * Generates Open Data Contract Standard (ODCS v2.2.0) YAML representation.
 */
export function generateODCS(architecture: DataArchitecture, internalConnections: InternalConnection[]): string {
  const sanitize = (str: string) => str.toLowerCase().replace(/[^a-z0-9_]/g, '_');

  let yaml = `# ==============================================================================
# Open Data Contract Standard (ODCS) - Version 2.2.0
# Generated by DAT-Web Architecture Studio
# ==============================================================================
version: 2.2.0
kind: DataContract
id: urn:datacontract:${sanitize(architecture.name || 'data_architecture')}
info:
  title: "${architecture.name || 'Data Architecture Model'}"
  version: 1.0.0
  description: "Enterprise data contract automatically synthesized from DAT-Web visual topology."
  status: active
  owner: "Data Architecture Team"

servers:
  production:
    type: cloud
    environment: prod
    description: "Production data pipeline environment"

models:
`;

  architecture.dataNodes.forEach(node => {
    const nodeKey = sanitize(node.name || node.id);
    const verifyElements = node.behaviouralElements.filter(el => el.type === 'VerifyData');
    const storageElements = node.behaviouralElements.filter(el => 
      ['RelationalDB', 'Store', 'Save', 'DocumentOriented', 'ColumnOriented', 'KeyValue', 'File_System'].includes(el.type)
    );
    const processElements = node.behaviouralElements.filter(el => 
      !['VerifyData', 'ReceiveData', 'SendData'].includes(el.type)
    );

    yaml += `  ${nodeKey}:
    name: "${node.name}"
    description: "Data node component: ${node.name}"
    type: ${storageElements.length > 0 ? 'storage_entity' : 'pipeline_service'}
    tags:
      - dat-web
      - ${storageElements.length > 0 ? 'storage' : 'processing'}
    fields:
`;

    if (node.messagePorts.length === 0) {
      yaml += `      - name: payload
        type: object
        description: "Default payload stream"
        required: true
`;
    } else {
      node.messagePorts.forEach(port => {
        yaml += `      - name: ${sanitize(port.name)}
        type: ${port.type === 'input' ? 'stream_input' : 'stream_output'}
        description: "${port.type.toUpperCase()} interface: ${port.name}"
        required: true
`;
      });
    }

    // Quality rules from VerifyData elements
    const qualityRules: { type: string; description: string }[] = [];
    verifyElements.forEach(vel => {
      const metrics: string[] = vel.properties?.QualityMetrics || [];
      const desc: string = vel.properties?.desc || '';
      metrics.forEach(metric => {
        qualityRules.push({
          type: metric.toLowerCase(),
          description: desc || `Ensures ${metric} standard on ${node.name}`
        });
      });
    });

    if (qualityRules.length > 0) {
      yaml += `    quality:
`;
      qualityRules.forEach(q => {
        yaml += `      - type: ${q.type}
        description: "${q.description}"
        severity: error
`;
      });
    }

    if (processElements.length > 0) {
      yaml += `    operations:
`;
      processElements.forEach(op => {
        yaml += `      - id: ${op.id}
        name: "${op.name}"
        type: "${op.type}"
`;
      });
    }

    yaml += '\n';
  });

  // Data Lineage / Service SLA terms
  yaml += `# ------------------------------------------------------------------------------
# Topology & Inter-Service Bindings
# ------------------------------------------------------------------------------
serviceLevelAgreement:
  availability: "99.9%"
  freshness: "1 hour"
  latency: "15 minutes"

dataFlows:
`;

  architecture.connections.forEach(conn => {
    const srcNode = architecture.dataNodes.find(n => n.id === conn.sourceNodeId)?.name || conn.sourceNodeId;
    const tgtNode = architecture.dataNodes.find(n => n.id === conn.targetNodeId)?.name || conn.targetNodeId;
    yaml += `  - id: ${conn.id}
    source: "${srcNode}"
    target: "${tgtNode}"
    label: "${conn.label || 'Data Flow'}"
`;
  });

  return yaml;
}

/**
 * Generates Mermaid.js flowchart markdown diagram.
 */
export function generateMermaid(architecture: DataArchitecture, internalConnections: InternalConnection[]): string {
  const sanitize = (id: string) => id.replace(/[^a-zA-Z0-9_]/g, '_');

  let mm = `flowchart LR
    %% DAT-Web Architecture Flowchart
    classDef nodeBox fill:#f8fafc,stroke:#94a3b8,stroke-width:2px,rx:8px,ry:8px;
    classDef processElem fill:#dbeafe,stroke:#3b82f6,stroke-width:1.5px,rx:5px,ry:5px;
    classDef storeElem fill:#dcfce7,stroke:#10b981,stroke-width:1.5px,rx:5px,ry:5px;
    classDef verifyElem fill:#fef3c7,stroke:#f59e0b,stroke-width:1.5px,rx:5px,ry:5px;
    classDef portStyle fill:#e2e8f0,stroke:#64748b,stroke-width:1px;

`;

  // Subgraphs for each DataNode
  architecture.dataNodes.forEach(node => {
    const sNodeId = sanitize(node.id);
    mm += `    subgraph ${sNodeId} ["📦 ${node.name}"]\n`;
    mm += `        direction TB\n`;

    if (node.behaviouralElements.length === 0) {
      mm += `        ${sNodeId}_empty["(Empty internal pipeline)"]\n`;
    } else {
      node.behaviouralElements.forEach(el => {
        const sElId = sanitize(el.id);
        const icon = el.type === 'VerifyData' ? '✅' :
                     el.type === 'Process' ? '⚙️' :
                     el.type === 'Store' || el.type === 'Save' ? '💿' :
                     el.type === 'Analyze' ? '🔍' :
                     el.type === 'Ingest' ? '📥' : '📋';
        
        let styleClass = 'processElem';
        if (el.type === 'VerifyData') styleClass = 'verifyElem';
        else if (['Store', 'Save', 'RelationalDB', 'DocumentOriented'].includes(el.type)) styleClass = 'storeElem';

        mm += `        ${sElId}["${icon} ${el.name} <br/><small>${el.type}</small>"]:::${styleClass}\n`;
      });

      // Internal connections for this node
      const nodeInternalConns = internalConnections.filter(c => c.nodeId === node.id);
      nodeInternalConns.forEach(conn => {
        const sSrc = sanitize(conn.sourceElementId);
        const sTgt = sanitize(conn.targetElementId);
        mm += `        ${sSrc} -.-> ${sTgt}\n`;
      });
    }

    mm += `    end\n    class ${sNodeId} nodeBox;\n\n`;
  });

  // External connections
  if (architecture.connections.length > 0) {
    mm += `    %% External Inter-Node Connections\n`;
    architecture.connections.forEach(conn => {
      const sSrcNode = sanitize(conn.sourceNodeId);
      const sTgtNode = sanitize(conn.targetNodeId);
      const label = conn.label ? `|"${conn.label}"|` : '';
      mm += `    ${sSrcNode} ==> ${label} ${sTgtNode}\n`;
    });
  }

  return mm;
}

/**
 * Generates dbt (Data Build Tool) project artifacts:
 * - sources.yml
 * - transformation SQL models
 * - schema.yml with generic data quality tests
 */
export function generateDbtArtifacts(architecture: DataArchitecture): {
  sourcesYml: string;
  schemaYml: string;
  modelsSql: Record<string, string>;
} {
  const sanitize = (s: string) => s.toLowerCase().replace(/[^a-z0-9_]/g, '_');

  // 1. sources.yml
  let sourcesYml = `version: 2

sources:
  - name: dat_sources
    description: "Raw source pipelines ingested into DAT architecture"
    tables:
`;

  architecture.dataNodes.forEach(node => {
    const inputPorts = node.messagePorts.filter(p => p.type === 'input');
    if (inputPorts.length > 0 || node.behaviouralElements.some(e => e.type === 'Ingest' || e.type === 'ReceiveData')) {
      sourcesYml += `      - name: ${sanitize(node.name)}_source
        description: "Raw source stream for ${node.name}"
        columns:
`;
      inputPorts.forEach(port => {
        sourcesYml += `          - name: ${sanitize(port.name)}
            description: "${port.name} input channel"
`;
      });
      if (inputPorts.length === 0) {
        sourcesYml += `          - name: raw_payload
            description: "Raw ingested event payload"
`;
      }
    }
  });

  // 2. Models SQL
  const modelsSql: Record<string, string> = {};

  architecture.dataNodes.forEach(node => {
    const modelName = `stg_${sanitize(node.name)}`;
    const upstreamConnections = architecture.connections.filter(c => c.targetNodeId === node.id);
    const verifyElements = node.behaviouralElements.filter(e => e.type === 'VerifyData');

    let sql = `-- Model: ${modelName}
-- Generated from DAT-Web Data Node: ${node.name}

with source_data as (
`;

    if (upstreamConnections.length > 0) {
      const upNode = architecture.dataNodes.find(n => n.id === upstreamConnections[0].sourceNodeId);
      const upModelName = upNode ? `stg_${sanitize(upNode.name)}` : 'raw_input';
      sql += `    select * from {{ ref('${upModelName}') }}\n`;
    } else {
      sql += `    select * from {{ source('dat_sources', '${sanitize(node.name)}_source') }}\n`;
    }

    sql += `),

transformed as (
    select
        id,
        current_timestamp as processed_at,
        '${node.name}' as pipeline_node
    from source_data
`;

    if (verifyElements.length > 0) {
      sql += `    -- Verification checkpoint: ${verifyElements.map(e => e.name).join(', ')}\n`;
    }

    sql += `)

select * from transformed;
`;

    modelsSql[`${modelName}.sql`] = sql;
  });

  // 3. schema.yml with tests mapped from VerifyData metrics
  let schemaYml = `version: 2

models:
`;

  architecture.dataNodes.forEach(node => {
    const modelName = `stg_${sanitize(node.name)}`;
    const verifyElements = node.behaviouralElements.filter(e => e.type === 'VerifyData');
    
    schemaYml += `  - name: ${modelName}
    description: "Transformation model for ${node.name}"
    columns:
      - name: id
        description: "Primary key identifier"
        tests:
`;

    const testSet = new Set<string>();
    verifyElements.forEach(vel => {
      const metrics: string[] = vel.properties?.QualityMetrics || [];
      if (metrics.includes('Uniqueness')) testSet.add('unique');
      if (metrics.includes('Completeness')) testSet.add('not_null');
      if (metrics.includes('Validity')) testSet.add('not_null');
    });

    if (testSet.size === 0) {
      testSet.add('not_null');
    }

    testSet.forEach(t => {
      schemaYml += `          - ${t}\n`;
    });
  });

  return { sourcesYml, schemaYml, modelsSql };
}

/**
 * Generates an Executive Markdown Architecture Specification Report.
 */
export function generateArchitectureReport(architecture: DataArchitecture, internalConnections: InternalConnection[]): string {
  const totalElements = architecture.dataNodes.reduce((sum, n) => sum + n.behaviouralElements.length, 0);
  const totalInputs = architecture.dataNodes.reduce((sum, n) => sum + n.messagePorts.filter(p => p.type === 'input').length, 0);
  const totalOutputs = architecture.dataNodes.reduce((sum, n) => sum + n.messagePorts.filter(p => p.type === 'output').length, 0);
  const totalVerifications = architecture.dataNodes.reduce((sum, n) => sum + n.behaviouralElements.filter(e => e.type === 'VerifyData').length, 0);

  let doc = `# Executive Architecture Specification: ${architecture.name}

*Generated by DAT-Web Architecture Studio on ${new Date().toISOString().split('T')[0]}*

---

## 1. Overview & Topology Metrics

| Metric | Count | Description |
| :--- | :--- | :--- |
| **Data Nodes** | ${architecture.dataNodes.length} | Top-level system boundaries and microservices |
| **Behavioural Elements** | ${totalElements} | Discrete ingestion, compute, and storage modules |
| **Input Ports** | ${totalInputs} | External stream and event consumers |
| **Output Ports** | ${totalOutputs} | External stream and event producers |
| **Inter-Node Flows** | ${architecture.connections.length} | Asynchronous and synchronous bus connections |
| **Intra-Node Wirings** | ${internalConnections.length} | Internal pipelines connecting ports and processors |
| **Quality Verifications** | ${totalVerifications} | Active data validation & SLA check nodes |

---

## 2. Component Inventory

`;

  architecture.dataNodes.forEach((node, idx) => {
    doc += `### 2.${idx + 1} Node: ${node.name} (ID: \`${node.id}\`)

* **Dimensions**: ${node.size.width}px × ${node.size.height}px at position (${node.position.x}, ${node.position.y})
* **Message Interfaces**:
`;
    if (node.messagePorts.length === 0) {
      doc += `  * *No ports assigned.* \n`;
    } else {
      node.messagePorts.forEach(port => {
        doc += `  * \`${port.type.toUpperCase()}\`: **${port.name}** (ID: \`${port.id}\`)\n`;
      });
    }

    doc += `* **Internal Operations (${node.behaviouralElements.length})**:\n`;
    if (node.behaviouralElements.length === 0) {
      doc += `  * *Empty internal behavioral area.* \n`;
    } else {
      node.behaviouralElements.forEach(el => {
        doc += `  * **${el.name}** (Type: \`${el.type}\`)\n`;
        if (el.type === 'VerifyData' && el.properties?.QualityMetrics?.length > 0) {
          doc += `    * *Active Quality Metrics*: ${el.properties.QualityMetrics.join(', ')}\n`;
          if (el.properties.desc) {
            doc += `    * *Description*: ${el.properties.desc}\n`;
          }
        }
      });
    }

    doc += '\n';
  });

  doc += `---

## 3. Data Flow Lineage

| Flow ID | Source Component | Target Component | Wire Label |
| :--- | :--- | :--- | :--- |
`;

  if (architecture.connections.length === 0) {
    doc += `| *None* | *None* | *None* | *No external connections declared* |\n`;
  } else {
    architecture.connections.forEach(conn => {
      const srcNode = architecture.dataNodes.find(n => n.id === conn.sourceNodeId)?.name || conn.sourceNodeId;
      const tgtNode = architecture.dataNodes.find(n => n.id === conn.targetNodeId)?.name || conn.targetNodeId;
      doc += `| \`${conn.id}\` | **${srcNode}** | **${tgtNode}** | ${conn.label || 'Data Flow'} |\n`;
    });
  }

  doc += `\n---
*End of Architecture Report.*
`;

  return doc;
}

/**
 * Generates clean standalone SVG file content representing the full canvas diagram.
 */
export function generateCanvasSvg(architecture: DataArchitecture): string {
  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;

  if (architecture.dataNodes.length === 0) {
    return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 400" width="600" height="400">
      <rect width="100%" height="100%" fill="#f8fafc"/>
      <text x="300" y="200" text-anchor="middle" fill="#94a3b8" font-family="sans-serif" font-size="16">Empty Architecture Model</text>
    </svg>`;
  }

  architecture.dataNodes.forEach(node => {
    minX = Math.min(minX, node.position.x);
    minY = Math.min(minY, node.position.y);
    maxX = Math.max(maxX, node.position.x + node.size.width);
    maxY = Math.max(maxY, node.position.y + node.size.height);
  });

  const pad = 60;
  const width = Math.max(800, maxX - minX + pad * 2);
  const height = Math.max(600, maxY - minY + pad * 2);
  const offsetX = pad - minX;
  const offsetY = pad - minY;

  let svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" width="${width}" height="${height}" font-family="system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif">
  <defs>
    <marker id="svg-arrow" markerWidth="8" markerHeight="6" refX="7" refY="3" orient="auto">
      <polygon points="0 0, 8 3, 0 6" fill="#3B82F6"/>
    </marker>
    <filter id="shadow" x="-5%" y="-5%" width="115%" height="115%">
      <feDropShadow dx="0" dy="4" stdDeviation="4" flood-opacity="0.08"/>
    </filter>
  </defs>

  <rect width="100%" height="100%" fill="#f8fafc"/>

  <!-- Connections -->
  <g id="connections">
`;

  architecture.connections.forEach(conn => {
    const srcNode = architecture.dataNodes.find(n => n.id === conn.sourceNodeId);
    const tgtNode = architecture.dataNodes.find(n => n.id === conn.targetNodeId);
    if (!srcNode || !tgtNode) return;

    const srcPort = srcNode.messagePorts.find(p => p.id === conn.sourcePortId);
    const tgtPort = tgtNode.messagePorts.find(p => p.id === conn.targetPortId);
    if (!srcPort || !tgtPort) return;

    const sx = srcNode.position.x + srcPort.position.x + offsetX;
    const sy = srcNode.position.y + srcPort.position.y + offsetY;
    const tx = tgtNode.position.x + tgtPort.position.x + offsetX;
    const ty = tgtNode.position.y + tgtPort.position.y + offsetY;

    const dx = Math.abs(tx - sx) * 0.5;
    const d = `M ${sx} ${sy} C ${sx + dx} ${sy}, ${tx - dx} ${ty}, ${tx} ${ty}`;

    svg += `    <path d="${d}" stroke="#3B82F6" stroke-width="2.5" fill="none" marker-end="url(#svg-arrow)"/>\n`;
    if (conn.label) {
      svg += `    <text x="${(sx + tx) / 2}" y="${(sy + ty) / 2 - 8}" text-anchor="middle" fill="#475569" font-size="12" font-weight="500">${conn.label}</text>\n`;
    }
  });

  svg += `  </g>\n\n  <!-- Data Nodes -->\n  <g id="nodes">\n`;

  architecture.dataNodes.forEach(node => {
    const nx = node.position.x + offsetX;
    const ny = node.position.y + offsetY;
    const nw = node.size.width;
    const nh = node.size.height;

    svg += `    <!-- Node: ${node.name} -->
    <g transform="translate(${nx}, ${ny})" filter="url(#shadow)">
      <rect width="${nw}" height="${nh}" rx="8" fill="#ffffff" stroke="#cbd5e1" stroke-width="1.5"/>
      <rect width="${nw}" height="36" rx="8" fill="#f1f5f9"/>
      <rect y="28" width="${nw}" height="8" fill="#f1f5f9"/>
      <line x1="0" y1="36" x2="${nw}" y2="36" stroke="#e2e8f0" stroke-width="1"/>
      <text x="14" y="23" font-size="13" font-weight="600" fill="#1e293b">${node.name}</text>
`;

    // Elements inside
    if (node.isExpanded) {
      node.behaviouralElements.forEach(el => {
        const ex = el.position.x;
        const ey = el.position.y + 40;
        const ew = el.size.width;
        const eh = el.size.height;

        const isVerify = el.type === 'VerifyData';
        const fill = isVerify ? '#ecfdf5' : '#eff6ff';
        const stroke = isVerify ? '#10b981' : '#3b82f6';
        const textFill = isVerify ? '#065f46' : '#1e40af';

        svg += `      <g transform="translate(${ex}, ${ey})">
        <rect width="${ew}" height="${eh}" rx="6" fill="${fill}" stroke="${stroke}" stroke-width="1"/>
        <text x="${ew / 2}" y="${eh / 2 + 4}" text-anchor="middle" font-size="11" font-weight="500" fill="${textFill}">${el.name}</text>
      </g>
`;
      });
    }

    // Ports
    node.messagePorts.forEach(port => {
      const px = port.position.x;
      const py = port.position.y;
      const color = port.type === 'input' ? '#10B981' : '#EF4444';
      svg += `      <circle cx="${px}" cy="${py}" r="5" fill="${color}" stroke="#ffffff" stroke-width="1.5"/>\n`;
    });

    svg += `    </g>\n`;
  });

  svg += `  </g>\n</svg>`;
  return svg;
}

/**
 * Generates an executable Apache Airflow 2.x DAG Python script.
 */
export function generateAirflowDag(architecture: DataArchitecture): string {
  const sanitize = (s: string) => s.toLowerCase().replace(/[^a-z0-9_]/g, '_');
  const dagId = sanitize(architecture.name || 'data_architecture_pipeline');

  let py = `"""
Apache Airflow DAG: ${architecture.name}
Synthesized automatically by DAT-Web Architecture Studio.
"""

from datetime import datetime, timedelta
from airflow import DAG
from airflow.operators.python import PythonOperator

default_args = {
    'owner': 'data_platform',
    'depends_on_past': False,
    'start_date': datetime(2026, 1, 1),
    'email_on_failure': True,
    'email': ['data-alerts@example.com'],
    'retries': 2,
    'retry_delay': timedelta(minutes=5),
}

def execute_pipeline_step(node_name: str, operations: list):
    print(f"Executing pipeline step for: {node_name}")
    for op in operations:
        print(f" -> Running operation: {op}")
    return True

with DAG(
    dag_id='${dagId}',
    default_args=default_args,
    description='Automated workflow for ${architecture.name}',
    schedule_interval='@daily',
    catchup=False,
    max_active_runs=1,
    tags=['dat-web', 'data-contract', 'generated'],
) as dag:

`;

  architecture.dataNodes.forEach(node => {
    const taskId = `task_${sanitize(node.name)}`;
    const ops = node.behaviouralElements.map(e => `${e.name} (${e.type})`);
    const opsJson = JSON.stringify(ops);

    py += `    ${taskId} = PythonOperator(
        task_id='${taskId}',
        python_callable=execute_pipeline_step,
        op_kwargs={
            'node_name': '${node.name}',
            'operations': ${opsJson}
        },
        doc_md="""### ${node.name}
Components: ${ops.join(', ') || 'No operations'}
"""
    )\n\n`;
  });

  if (architecture.connections.length > 0) {
    py += `    # Pipeline Task Dependencies\n`;
    architecture.connections.forEach(conn => {
      const srcNode = architecture.dataNodes.find(n => n.id === conn.sourceNodeId);
      const tgtNode = architecture.dataNodes.find(n => n.id === conn.targetNodeId);
      if (srcNode && tgtNode) {
        py += `    task_${sanitize(srcNode.name)} >> task_${sanitize(tgtNode.name)}\n`;
      }
    });
  }

  return py;
}

/**
 * Generates Great Expectations Suite (JSON) from VerifyData quality rules.
 */
export function generateGreatExpectationsSuite(architecture: DataArchitecture): string {
  const sanitize = (s: string) => s.toLowerCase().replace(/[^a-z0-9_]/g, '_');
  const expectations: any[] = [];

  architecture.dataNodes.forEach(node => {
    const verifyElements = node.behaviouralElements.filter(e => e.type === 'VerifyData');
    verifyElements.forEach(vel => {
      const metrics: string[] = vel.properties?.QualityMetrics || [];
      const col = node.messagePorts[0]?.name ? sanitize(node.messagePorts[0].name) : 'id';

      metrics.forEach(metric => {
        switch (metric) {
          case 'Completeness':
            expectations.push({
              expectation_type: 'expect_column_values_to_not_be_null',
              kwargs: { column: col },
              meta: { component: node.name, rule: 'Completeness' }
            });
            break;
          case 'Uniqueness':
            expectations.push({
              expectation_type: 'expect_column_values_to_be_unique',
              kwargs: { column: col },
              meta: { component: node.name, rule: 'Uniqueness' }
            });
            break;
          case 'Validity':
            expectations.push({
              expectation_type: 'expect_column_values_to_be_in_type_list',
              kwargs: { column: col, type_list: ['STRING', 'VARCHAR', 'INTEGER', 'FLOAT'] },
              meta: { component: node.name, rule: 'Validity' }
            });
            break;
          case 'Timeliness':
            expectations.push({
              expectation_type: 'expect_column_max_to_be_between',
              kwargs: { column: 'timestamp', min_value: 'now() - interval 1 day' },
              meta: { component: node.name, rule: 'Timeliness' }
            });
            break;
          default:
            expectations.push({
              expectation_type: 'expect_table_columns_to_match_ordered_list',
              kwargs: { column_list: node.messagePorts.map(p => sanitize(p.name)) },
              meta: { component: node.name, rule: metric }
            });
            break;
        }
      });
    });
  });

  const suite = {
    expectation_suite_name: `${sanitize(architecture.name)}_quality_suite`,
    data_asset_type: 'Dataset',
    meta: {
      generated_by: 'DAT-Web Architecture Studio',
      generated_at: new Date().toISOString(),
      architecture_id: architecture.id
    },
    expectations: expectations.length > 0 ? expectations : [
      {
        expectation_type: 'expect_table_row_count_to_be_between',
        kwargs: { min_value: 1, max_value: null },
        meta: { rule: 'Basic Integrity' }
      }
    ]
  };

  return JSON.stringify(suite, null, 2);
}

